### PR TITLE
Refactor workflows

### PR DESCRIPTION
**Pull request by OlivierJM**

### CODE REVIEW

**Comment by YewoMhango** [comment]
Oh, okay, I see. For me, I also encountered that error and it somehow got fixed when I ran `rm yarn.lock && yarn`. I guess we could just publish it as a separate package on NPM to avoid these issues

**Comment by brianmuks** [comment]
I actually wanted to suggest that we use an  Adobe package.  It's good I
have used it before

**Comment by YewoMhango** [comment]
> > Oh, okay, I see. For me, I also encountered that error and it somehow got fixed when I ran `rm yarn.lock && yarn`. I guess we could just publish it as a separate package on NPM to avoid these issues
> 
> This fixed the build, we can publish our own package later. I plan to move this repo to the main organization here https://github.com/SparkEdUAB this way it can be together with other repository.

Okay, great

**Comment by YewoMhango** [comment]
> I actually wanted to suggest that we use an Adobe package. It's good I have used it before

That seems like it would be very helpful

**Pull request merged**
