### PR TITLE
Fix - Convert endpoints to GET 

### LINKED ISSUE #85: URGENT - Convert endpoints to GET
For better performance and to be able to achieve this #60 we need to have fetch endpoints as GET instead of POST. 

For dashboard

- fetch courses
- fetch units
- fetch topics
- fetch media contents

For client

- fetch units
- fetch topics
- fetch media contents
- fetch individual media content. 

@brianmuks this is blocking #60 it would be great if we can start on this especially dashboard links.

### PR DESCRIPTION
**Pull request by OlivierJM**
Fixes #85

### CODE REVIEW

**Comment by brianmuks** [comment]
@OlivierJM I am on it.

**Comment by brianmuks** [comment]
@OlivierJM can I merge this ?

**Comment by brianmuks** [comment]
> @OlivierJM yeah, wait a bit. I got sidetracked with something else here, but I'm back on it and should be done soon

@YewoMhango by 'wait a bit' do you mean we shouldn’t merge ?

**Comment by YewoMhango** [comment]
@OlivierJM so I guess I'll now start working on #60

**Pull request merged**
