### PR TITLE
setup docker

### PR DESCRIPTION
**Pull request by OlivierJM**
If you are on Mac, I strongly recommend you install this https://orbstack.dev/ because docker for mac is extremely slow, after setup you can simply run `docker-compose up dev` this is already coupled with mongodb.

### CODE REVIEW

**Review by brianmuks — APPROVED** [review]

**Review by brianmuks — COMMENTED** [review]
@OlivierJM Can we set it up so that if the app is in development, it uses the local MongoDB instance, otherwise it connects to the live MongoDB instance?

**Comment by brianmuks** [comment]
Please help me understand how to go about this. Do we need to manually edit the `.env` file ?

**Comment by mikemtdev** [comment]
HI @OlivierJM, 
I've checked it out it's able to spin up containers. 
I just have issues creating an account.

**Comment by brianmuks** [comment]
> > Please help me understand how to go about this. Do we need to manually edit the `.env` file ?
> 
> Yea you have to remove the MongoDB uri from the .env
> 
> I am trying to find a way to automate data seeding so that there will be some data when you setup the first time, maybe you can help out with that.

This is a good idea. Is it okay if we make this less of a priority seeing the amount of issues we have to complete before deadline ?

**Pull request merged**
